const BASE_URL = 'https://gateway.marvel.com:443/v1/public/characters';

const MAX_CHARACTERS_DEFAULT = 30;
const MAX_CHARACTERS_OPTIM = 50;
const MAX_CHARACTERS_TOP = 100;

const MAX_CHARACTER_COMICS = 10;

export {
  BASE_URL,
  MAX_CHARACTERS_DEFAULT,
  MAX_CHARACTERS_OPTIM,
  MAX_CHARACTERS_TOP,
  MAX_CHARACTER_COMICS,
};
